name: deploy node app to vps
on:
  push:
    branches: 
      - main
jobs:
    deploy: 
       runs-on: ubuntu-latest
       steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: deploy to vps
          uses: appleboy/ssh-action@1.0.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd /root/CI-CD-pipeline
              git pull origin main
              docker-compose up -d --build
